substituters = ["https://cache.ysun.co"]

systems = ["x86_64-linux", "aarch64-linux"]

include = ["checks.*.*", "devShells.*.*", "formatter.*", "packages.*.*"]

exclude = [
  "legacyPackages.*.*",     # unused
  "checks.aarch64-linux.*", # runner does not have kvm
]
