schema = 3

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.6.0'
    hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/beorn7/perks']
    version = 'v1.0.1'
    hash = 'sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.3'
    hash = 'sha256-y+QDUxGOKhugEMQLRUTZYT2C+wKqYHnMLJ44jbh7+JA='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v1.1.0'
    hash = 'sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4='

  [mod.'github.com/charmbracelet/log']
    version = 'v1.0.0'
    hash = 'sha256-Veo9gqSs/ZHFNERzXSCtQjovaIwdr8YZkCIJ7xfTEGY='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.8'
    hash = 'sha256-IyGyFE/grl7aNEZEMXzmUl+X7qb8HaMAfmJXWhoRLQQ='

  [mod.'github.com/charmbracelet/x/cellbuf']
    version = 'v0.0.15'
    hash = 'sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/cilium/ebpf']
    version = 'v0.22.0'
    hash = 'sha256-I2VWB3b2BjRAxZmbvE8Kk6N0nbJhb39Prhv9BpSLfJU='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.11.0'
    hash = 'sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.7.0'
    hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

  [mod.'github.com/gaissmai/bart']
    version = 'v0.30.0'
    hash = 'sha256-4ryvjMsEc53dW3Stp3yBlhMP3F6jyZQA+I6J6Vv3WYE='

  [mod.'github.com/go-logfmt/logfmt']
    version = 'v0.6.1'
    hash = 'sha256-+gUGmdR/QOsB9qKESLrsbq6tK2VssNT/kDbRFpgrZL4='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.4.1'
    hash = 'sha256-nY4QB5g4wsf/BNjtNBxzAbgE40kHDhYYYQMAQUHic60='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.24'
    hash = 'sha256-pmq8KKIb2+qMF3E1cR2B7NAj5joF2tZduyXjIfIlkTk='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.30'
    hash = 'sha256-2idyB8BVjqiwBOmBteKMTM9uBfr96g29k8hqJWjlndE='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/munnerz/goautoneg']
    version = 'v0.0.0-20191010083416-a7dc8b61c822'
    hash = 'sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q='

  [mod.'github.com/oschwald/maxminddb-golang/v2']
    version = 'v2.7.0'
    hash = 'sha256-MBwpR/MEfkG2sgkddhf3Lxhso68Jegw2d9eAGU4OsYg='

  [mod.'github.com/osrg/gobgp/v3']
    version = 'v3.37.0'
    hash = 'sha256-okiSm28hYGLaO/v69lUFjIzvNBPHFZ9yrlSdhpfYc1c='

  [mod.'github.com/prometheus/client_golang']
    version = 'v1.24.1'
    hash = 'sha256-HAOFVYyPiU7hVS1XXMMjkbGgTT7/UN0zVHXYOnjr7is='

  [mod.'github.com/prometheus/client_model']
    version = 'v0.6.3'
    hash = 'sha256-uYXpFkXMT4AXWJShrCRnu51vhGQAuAU3LFQhhGVJ+74='

  [mod.'github.com/prometheus/common']
    version = 'v0.72.0'
    hash = 'sha256-OXi+GGzrV31yeKtel2bImkF7PW4tKWyOcyTZB5WbkDI='

  [mod.'github.com/prometheus/procfs']
    version = 'v0.22.0'
    hash = 'sha256-TRwVHKgW4NnPuC6Me38OD57ccM8AfnS7IxtcAx2TAH4='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/vishvananda/netlink']
    version = 'v1.3.1'
    hash = 'sha256-xURBhfN6vit7GIrNkSy9bWE3JewfOWTG4hHTUN1zPWo='

  [mod.'github.com/vishvananda/netns']
    version = 'v0.0.5'
    hash = 'sha256-wYDmrmqdv9R8dAL5nuWJ+1Nh7fWWxdpd03UkLOtyJrk='

  [mod.'github.com/vmware/go-ipfix']
    version = 'v0.18.0'
    hash = 'sha256-M19FDSqpQyzU5VyKkDIx0Hc5KFNQfB9CyOnm+DKNwcU='

  [mod.'github.com/xo/terminfo']
    version = 'v1.2.0'
    hash = 'sha256-cLY+3xdncFQA7wPfh21Pex3Q9LA7dhRe+IyH0x6bQfM='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20260908205506-85c1c2202aba'
    hash = 'sha256-g/gNDzulP2hxBtZf3w2cASzcWbUAI6r0Q9zy5Q/wrRQ='

  [mod.'golang.org/x/sys']
    version = 'v0.48.0'
    hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.12'
    hash = 'sha256-MKd0AdkWEe2A79mGPzOY5I76nMqTsGJKQNPJOKyOwkQ='
