// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rfmRfmConfig struct {
	_                 structs.HostLayout
	SampleRate        uint32
	Flags             uint32
	InactiveTimeoutNs uint32
	Pad               uint32
}

type rfmRfmIfaceKey struct {
	_       structs.HostLayout
	Ifindex uint32
	Dir     uint8
	Proto   uint8
	Pad     uint16
}

type rfmRfmIfaceValue struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

// loadRfm returns the embedded CollectionSpec for rfm.
func loadRfm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RfmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rfm: %w", err)
	}

	return spec, err
}

// loadRfmObjects loads rfm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rfmObjects
//	*rfmPrograms
//	*rfmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRfmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRfm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rfmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rfmSpecs struct {
	rfmProgramSpecs
	rfmMapSpecs
	rfmVariableSpecs
}

// rfmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rfmProgramSpecs struct {
	RfmTcEgress  *ebpf.ProgramSpec `ebpf:"rfm_tc_egress"`
	RfmTcIngress *ebpf.ProgramSpec `ebpf:"rfm_tc_ingress"`
}

// rfmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rfmMapSpecs struct {
	RfmConfig     *ebpf.MapSpec `ebpf:"rfm_config"`
	RfmIfaceStats *ebpf.MapSpec `ebpf:"rfm_iface_stats"`
}

// rfmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rfmVariableSpecs struct {
}

// rfmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRfmObjects or ebpf.CollectionSpec.LoadAndAssign.
type rfmObjects struct {
	rfmPrograms
	rfmMaps
	rfmVariables
}

func (o *rfmObjects) Close() error {
	return _RfmClose(
		&o.rfmPrograms,
		&o.rfmMaps,
	)
}

// rfmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRfmObjects or ebpf.CollectionSpec.LoadAndAssign.
type rfmMaps struct {
	RfmConfig     *ebpf.Map `ebpf:"rfm_config"`
	RfmIfaceStats *ebpf.Map `ebpf:"rfm_iface_stats"`
}

func (m *rfmMaps) Close() error {
	return _RfmClose(
		m.RfmConfig,
		m.RfmIfaceStats,
	)
}

// rfmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRfmObjects or ebpf.CollectionSpec.LoadAndAssign.
type rfmVariables struct {
}

// rfmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRfmObjects or ebpf.CollectionSpec.LoadAndAssign.
type rfmPrograms struct {
	RfmTcEgress  *ebpf.Program `ebpf:"rfm_tc_egress"`
	RfmTcIngress *ebpf.Program `ebpf:"rfm_tc_ingress"`
}

func (p *rfmPrograms) Close() error {
	return _RfmClose(
		p.RfmTcEgress,
		p.RfmTcIngress,
	)
}

func _RfmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rfm_bpfeb.o
var _RfmBytes []byte
